[package]
name = "sqlgrep"
version = "0.1.0"
authors = ["Anton Jansson <anton_jansson@live.se>"]
edition = "2018"

[lib]
name = "sqlgrep"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
structopt = "0.3"
ctrlc = "3.0"
rustyline = "6.3.0"
rustyline-derive = "0.3.1"
fnv = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "full_pipeline"
harness = false