[package]
name = "sqlgrep"
version = "0.6.0"
authors = ["Anton Jansson <anton_jansson@live.se>"]
edition = "2018"
description = "sqlgrep = SQL + grep + tail -f"
license = "MIT"
homepage = "https://github.com/svenslaggare/sqlgrep"

[lib]
name = "sqlgrep"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
structopt = "0.3"
ctrlc = "3.0"
rustyline = "9.0.0"
rustyline-derive = "0.5.0"
fnv = "1.0"
itertools = "0.10.0"
serde_json = { version = "1", features = ["preserve_order"] }
chrono = "0.4.19"
cursive = "0.20"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "full_pipeline"
harness = false