name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  release-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      run: cargo build --release --verbose
    - name: Build Debian package
      run: cargo install cargo-deb && cargo deb
    - uses: actions/upload-artifact@v2
      with:
        name: sqlgrep_linux_x86_64
        path: target/release/sqlgrep
    - uses: actions/upload-artifact@v2
      with:
        name: sqlgrep_linux_x86_64_debian
        path: target/debian/
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  release-build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Release Build
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: sqlgrep_windows_2019_x86_64
          path: target/release/sqlgrep.exe
